# Generated by Django 4.1 on 2022-09-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_curso_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='turno',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mañana'), (2, 'Tarde'), (3, 'Noche')], default=1, verbose_name='Turno'),
            preserve_default=False,
        ),
    ]
