# Generated by Django 4.1 on 2022-09-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_curso_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesor_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
