# Generated by Django 4.1 on 2022-09-26 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='profesor_id',
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.profesor'),
        ),
    ]
